---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespce
---
apiVersion: v1
kind: Pod
metadata:
  name: namespce-demo
  namespace: my-namespce
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
