apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testing-replicaset
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 9
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - jenkins
      - key: ver
        operator: Exists
  template:
    metadata:
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx-replica
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP        
