apiVersion: v1
kind: ReplicationController
metadata:
  name: rep-cont
spec:
    minReadySeconds: 3
    replicas: 5
    selector:
      app: nginx
    template:
      metadata:
        name: nginx-repli
        labels:
          app: nginx
          ver: "1.23"
      spec:
        containers:
          - name: nginx-cont
            image: nginx
            ports:
              - containerPort: 80



