apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
      # Three types of ports for a service
      # nodePort - a static port assigned on each the node
      # port - port exposed internally in the cluster
      # targetPort - the container port to send requests to
    - name: webport
      nodePort: 31001
      port: 8081 # Expose to outside
      targetPort: 80