apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-cont
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: userone
        - name: MYSQL_PASSWORD
          value: passpass  
      ports:
        - containerPort: 3306

