apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: jenkins
        ver: 2.60.3
    spec:
      containers:
        - name: jenkins-dep
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: lb
      port: 31001 
      targetPort: 8080