apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-demo
  namespace: my-namespce
spec:
  schedule: "00 23 * * *"
  jobTemplate:
    metadata:
      labels:
        purpose: execution
      namespace: my-namespce
    spec:
      backoffLimit: 3 # Specifies the number of retries before marking this job failed. Defaults to 6
      template:
        metadata:
          labels:
            purpose: execution
          namespace: my-namespce
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpine-job
              image: alpine:3
              command: 
                - wget
                - https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar

  
