apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  containers:
    - name: mysql-cont
      image: mysql:8
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: huell
        - name: MYSQL_PASSWORD
          value: nonroot
      ports:
        - containerPort: 3306 
      VolumeMount:
        name: mysql-vol
        mountPath: /var/lib/mysql
  volumes:
    - name: mysql-vol
      emptyDir:       # emptyDir represents a temporary directory that shares a pod's lifetime.

