apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
      env: dev
  template:
    metadata:
      labels:
        app: jenkins
        env: dev
    spec:
      containers:
        - name: jenkins-rs
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi