apiVersion: v1
kind: Pod
metadata:
  name: test-init
spec:
  initContainers:
    - name: init-cont
      image: alpine:3
      command:
        - sleep
        - "30"
  containers:
    - name: my-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP