---
apiVersion: v1
kind: Pod
metadata:
  name: label-test1
  labels:
    app: nginx
    ver: "1.23"
spec:
  containers:
    - name: nginx-cont
      image: nginx:1.23
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: label-test2
  labels:
    app: nginx
    ver: "1.22" 
spec:
  containers:
    - name: nginx-cont2
      image: nginx:1.22
      ports:
        - containerPort: 80