apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx:1.23
      ports: 
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins
      name: jenkins-cont
      ports:
        - containerPort: 80
          protocol: TCP


