apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /tmp
          name: configmap-demo
  volumes: 
    configMap: 
      name: configmap-demo