apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /configmap/log.conf
          name: configmap-vol
  volumes:
    - name: configmap-vol
      configMap: 
        name: configmap-demo